### ISSUE TITLE
Return results with Artifacts

### ISSUE THREAD

**Issue by hallmatt** [joytocode/lighthouse-lambda#10]
Thanks for the great project! 

Is it possible to get artifacts returned in the results? It would be nice to be able to utilize the full json results. Lighthouse seems to include some helpful details there.

https://github.com/joytocode/lighthouse-lambda/blob/982d806c12fd738ded7e25341f5059edf811d8c2/lib/index.js#L24

**Comment by baocancode** [comment]
The old doc of https://github.com/GoogleChrome/lighthouse/blob/master/docs/readme.md#using-programmatically suggests to delete the artifacts because it is heavy. Since lighthouse-lambda@1.1.4, you can run `start({ saveArtifacts: true })` to keep the artifacts.

We will review it again when updating to Lighthouse 3.

**Comment by baocancode** [comment]
Fixed by #9.

**Comment by hallmatt** [comment]
Thanks!
